name: banners
version: 0.3.1
description: Package for dynamically displaying global banners at the top of the screen.
repository: https://github.com/marcelgarus/banners

environment:
  flutter: '>=3.0.0'
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
