name: banners
description: Package for dynamically displaying global banners at the top of the screen.
homepage: https://github.com/marcelgarus/banners
version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
